apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dcvl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0067-tenant/tkrw-pr714-0075-0067-app/devfile-sample-dcvl@sha256:e7ff1e7b1a4f804b3dcd36c68b4c168bb69888de6841fd9cf8e76025420b61ff
        name: my-nodejs
        resources: {}
status: {}
